---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: github-actions
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Github actions runners and their controller
  destinations:
    - name: two-tauers
      namespace: actions-runner-controller
    - name: two-tauers
      namespace: actions-runner-set
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - ghcr.io/actions/actions-runner-controller-charts #oci
    - https://github.com/two-tauers/argocd-config
status: {}
