---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: local-services
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Self hosted services to be exposed only to the local network
  destinations:
    - name: pibox
      namespace: local-services
    - name: two-tauers
      namespace: local-services
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/two-tauers/argocd-config
    - https://two-tauers.github.io/helm-charts
status: {}
