---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-volumes
  namespace: argocd
spec:
  generators:
  - list:
      elements: # create an application per cluster
        - cluster: pibox
        - cluster: two-tauers
  template:
    metadata:
      name: 'volumes-{{cluster}}'
      namespace: argocd
    spec:
      destination:
        namespace: argocd
        name: '{{cluster}}'
      source:
        path: './volumes/{{cluster}}/'
        repoURL: 'https://github.com/two-tauers/argocd-config'
        targetRevision: HEAD
        directory:
          recurse: true
          include: '*.yaml'
      project: meta
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        # only sync manually for now
        # automated:
        #   selfHeal: true
