---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: projects
    repoURL: 'https://github.com/two-tauers/argocd-config'
    targetRevision: HEAD
    directory:
      recurse: true
      include: '*.yaml'
  project: meta
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
