---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ArgoCD meta-project for managing itself
  destinations:
    - name: ''
      namespace: argocd
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/two-tauers/argocd-config
status: {}
