---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: meta
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ArgoCD meta-project for managing itself
  destinations:
    - namespace: argocd
      name: pibox
      server: 'https://kubernetes.default.svc'
    - namespace: argocd
      name: two-tauers
      server: 'https://192.168.0.100:6443'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - https://github.com/two-tauers/argocd-config
