---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
spec:
  destination:
    name: two-tauers
    namespace: actions-runner-controller
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.12.1
      chart: gha-runner-scale-set-controller
      helm:
        releaseName: arc
        valueFiles:
          - $values/applications/arc-values.yaml
    - repoURL: "https://github.com/two-tauers/argocd-config"
      targetRevision: HEAD
      ref: values
  project: github-actions
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/
      - ServerSideApply=true
