---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ars
spec:
  destination:
    name: two-tauers
    namespace: actions-runner-set
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.12.1
      chart: gha-runner-scale-set
      helm:
        releaseName: ars
        valueFiles:
          - $values/applications/ars-values.yaml
    - repoURL: "https://github.com/two-tauers/argocd-config"
      targetRevision: HEAD
      ref: values
  project: github-actions
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
