---
env:
  - name: PUID
    value: "100"
  - name: PGID
    value: "101"
  - name: TZ
    value: "Europe/London"

pvc:
  config: calibre-web-config
  library: calibre-web-library

service:
  type: ClusterIP
  port: 8083

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  hosts:
    - host: calibre.home
      paths:
        - path: /
          pathType: ImplementationSpecific
