apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
spec:
  destination:
    name: pibox
    namespace: nas
  source:
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.2.1
    chart: filebrowser
    helm:
      releaseName: filebrowser
      values: |
        filebrowser:
          sharePath: /tmp
        service:
          port: 80
        ingress:
          baseURL: "/files"
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
