apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebrowser
spec:
  destination:
    name: pibox
    namespace: nas
    server: ''
  source:
    path: ''
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.2.0
    chart: filebrowser
    helm:
      releaseName: filebrowser
      values: |
        filebrowser:
          sharePath: /tmp
  sources: []
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
