---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rsync
spec:
  destination:
    name: pibox
    namespace: nas
  source:
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.1.2
    chart: rsync
    helm:
      releaseName: rsync
      values: |
        rsync:
          sourcePath: /mnt/nas
          targetPath: /mnt/nas-backup
          cron: "0 * * * *"
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
