apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba
spec:
  destination:
    name: pibox
    namespace: nas
  source:
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.1.1
    chart: samba
    helm:
      releaseName: samba
      values: |
        samba:
          sharePath: /mnt/nas
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
