---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba
spec:
  destination:
    name: pibox
    namespace: nas
  source:
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.2.1
    chart: samba
    helm:
      releaseName: samba
      values: |
        samba:
          userSecret:
            # to be created manually
            # kubectl create secret generic samba-users -n nas --from-literal='USER1=<username>;<password>'
            create: false 
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
