apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba
spec:
  destination:
    name: pibox
    namespace: nas
  source:
    repoURL: 'https://two-tauers.github.io/helm-charts'
    targetRevision: 0.2.0
    chart: samba
    helm:
      releaseName: samba
      values: |
        samba:
          userSecret:
            create: false #to be created manually
  project: nas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
