---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-config-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/two-tauers/argocd-config
