---
apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii-helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://firefly-iii.github.io/kubernetes
