---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-community-helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://grafana-community.github.io/helm-charts
