---
apiVersion: v1
kind: Secret
metadata:
  name: minio-helm-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://charts.min.io/
