---
apiVersion: v1
kind: Secret
metadata:
  name: two-tauers-helm-charts-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://two-tauers.github.io/helm-charts
