---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-library
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /two-tauers/calibre-web-library
    server: pibox.local
    readOnly: false