---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web-library
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /two-tauers/calibre-web-library
    server: pibox.local
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-library
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: calibre-web-library
  resources:
    requests:
      storage: 800Gi