---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-db
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /two-tauers/firefly-iii-db
    server: pibox.local
    readOnly: false

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: firefly-iii-db-backup
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /two-tauers/firefly-iii-db-backup
    server: pibox.local
    readOnly: false
